### ISSUE TITLE
Facing issue while installing

### ISSUE THREAD

**Issue by tashfeenahmed** [armaldio/electron-bottom-most#3]
Here's what I'm getting when I try to install electron-bottom-most using: npm i -S electron-bottom-most

Please help.

```
> electron-bottom-most@0.3.0 install /Users/tashfeenahmed/Desktop/Projects/DesktopWidget/Electron/node_modules/electron-bottom-most
> node-gyp rebuild

  CXX(target) Release/obj.target/bottom-most/lib.o
../lib.cc:22:5: error: unknown type name 'HWND'
    HWND hwnd = NULL;
    ^
../lib.cc:38:13: error: use of undeclared identifier 'HWND'
    hwnd = (HWND)handle;
            ^
../lib.cc:40:34: error: use of undeclared identifier 'HWND_BOTTOM'
    bool ok = SetWindowPos(hwnd, HWND_BOTTOM, 0, 0, 0, 0, SWP_NOSIZE | SWP_NOMOVE | SWP_NOACTIVATE);
                                 ^
../lib.cc:40:59: error: use of undeclared identifier 'SWP_NOSIZE'
    bool ok = SetWindowPos(hwnd, HWND_BOTTOM, 0, 0, 0, 0, SWP_NOSIZE | SWP_NOMOVE | SWP_NOACTIVATE);
                                                          ^
../lib.cc:40:72: error: use of undeclared identifier 'SWP_NOMOVE'
    bool ok = SetWindowPos(hwnd, HWND_BOTTOM, 0, 0, 0, 0, SWP_NOSIZE | SWP_NOMOVE | SWP_NOACTIVATE);
                                                                       ^
../lib.cc:40:85: error: use of undeclared identifier 'SWP_NOACTIVATE'
    bool ok = SetWindowPos(hwnd, HWND_BOTTOM, 0, 0, 0, 0, SWP_NOSIZE | SWP_NOMOVE | SWP_NOACTIVATE);
                                                                                    ^
6 errors generated.
make: *** [Release/obj.target/bottom-most/lib.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 16.7.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/tashfeenahmed/Desktop/Projects/DesktopWidget/Electron/node_modules/electron-bottom-most
gyp ERR! node -v v7.8.0
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok 
npm WARN DesktopWidget@1.0.0 No repository field.
npm ERR! Darwin 16.7.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "-S" "electron-bottom-most"
npm ERR! node v7.8.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1

npm ERR! electron-bottom-most@0.3.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron-bottom-most@0.3.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron-bottom-most package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron-bottom-most
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron-bottom-most
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/tashfeenahmed/.npm/_logs/2018-07-25T20_02_33_684Z-debug.log
```

**Comment by Armaldio** [comment]
Hello,

Can you tell me you OS version, python version and node.js version ?

**Comment by tashfeenahmed** [comment]
MacOS Sierra 10.12.6 (16G29)
Python 2.7.10
Node.js v7.8.0

**Comment by Armaldio** [comment]
Sorry for late reply

This module is only compatible with Windows at this time but pR are welcome if you want to support MacOs
